(function () {
  var InterpolationPanel = {
    init: function (app) {
      this.app = app; this.view = document.getElementById("interpolationView");
      this.modelSelect = document.getElementById("interpolationModel");
      this.factorContainer = document.getElementById("interpolationFactor");
      this.factorCustom = document.getElementById("interpFactorCustom");
      this.startBtn = document.getElementById("startInterpolateBtn");
      this.cancelBtn = document.getElementById("cancelInterpolateBtn");
      this._sourceInfo = null;
      this.bindEvents(); this._renderSafe("modelInfo"); this._renderSafe("factorInfo");
    },
    getFactor: function () { if (this.factorCustom && this.factorCustom.value) { var v = parseInt(this.factorCustom.value, 10); if (v >= 2 && v <= 64) return v; } if (this.factorContainer) { var a = this.factorContainer.querySelector(".factor-btn.active"); if (a) return parseInt(a.getAttribute("data-value"), 10); } return 2; },
    bindEvents: function () { var s = this; if (this.startBtn) this.startBtn.addEventListener("click", function () { s.addToQueue(); }); var pv = document.getElementById("previewInterpolateBtn"); if (pv) pv.addEventListener("click", function () { s.startPreview(); }); if (this.cancelBtn) this.cancelBtn.addEventListener("click", function () { window.QueueManager.cancelAll(); }); if (this.modelSelect) this.modelSelect.addEventListener("change", function () { s._renderSafe("modelInfo"); }); if (this.factorContainer) { this.factorContainer.addEventListener("click", function (e) { var el = e.target; while (el && el !== s.factorContainer) { if (el.classList && el.classList.contains("factor-btn")) break; el = el.parentElement; } if (!el || el === s.factorContainer) return; var btns = s.factorContainer.querySelectorAll(".factor-btn"); for (var i = 0; i < btns.length; i++) btns[i].classList.remove("active"); el.classList.add("active"); if (s.factorCustom) s.factorCustom.value = ""; s._renderSafe("factorInfo"); }); } if (this.factorCustom) { this.factorCustom.addEventListener("input", function () { var btns = s.factorContainer.querySelectorAll(".factor-btn"); for (var i = 0; i < btns.length; i++) btns[i].classList.remove("active"); s._renderSafe("factorInfo"); }); } var enableTargetSize = document.getElementById("interpEnableTargetSize"); var targetSizeInput = document.getElementById("interpTargetSize"); var targetSizeRow = enableTargetSize ? enableTargetSize.closest(".toggle-row") : null; if (enableTargetSize && targetSizeInput) { enableTargetSize.addEventListener("change", function () { targetSizeInput.disabled = !this.checked; }); if (targetSizeRow) { targetSizeRow.addEventListener("click", function (e) { if (e.target !== enableTargetSize) { enableTargetSize.checked = !enableTargetSize.checked; enableTargetSize.dispatchEvent(new Event("change")); } }); } } window.QueueManager.onUpdate(function () { s._updateButtons(window.QueueManager.isRunning()); }); },
    refreshLayerInfo: function () { var s = this; if (!window.__adobe_cep__ || !window.__adobe_cep__.evalScript) { if (s._sourceInfo !== null) { s._sourceInfo = null; s._renderSafe("layerInfo"); } return; } if (this._fetching) return; this._fetching = true; window.__adobe_cep__.evalScript("getSelectedLayerInfo()", function (r) { s._fetching = false; var raw = r || "{}"; if (raw === s._lastRaw) return; s._lastRaw = raw; try { s._sourceInfo = JSON.parse(raw); } catch (e) { s._sourceInfo = null; } s._renderSafe("layerInfo"); s._renderSafe("factorInfo"); }); },
    _renderSafe: function (w) { try { if (w === "layerInfo") this.renderLayerInfo(); else if (w === "factorInfo") this.renderFactorInfo(); else if (w === "modelInfo") this.renderModelInfo(); } catch (e) {} },
    renderLayerInfo: function () { var el = document.getElementById("interpLayerInfo"); if (!el) return; var s = this._sourceInfo; if (!s || !s.ok) { el.innerHTML = '<span class="meta-strip meta-strip-dim"><i class="fa-solid fa-layer-group"></i> Select a footage layer</span>'; return; } var w = s.width || 0, h = s.height || 0, fps = s.frameRate || s.compFrameRate || 0, dur = s.layerDuration || s.compDuration || s.duration || 0, frames = Math.round((dur || 0) * fps), parts = []; if (w > 0 && h > 0) parts.push('<span>' + w + '<b>\u00d7</b>' + h + '</span>'); if (fps > 0) parts.push('<span>' + fps.toFixed(2) + ' fps</span>'); if (frames > 0) parts.push('<span>' + frames + ' frames</span>'); el.innerHTML = '<span class="meta-strip"><i class="fa-solid fa-film"></i> <b>' + esc(s.layerName || s.name || "") + '</b>' + (parts.length ? ' \u00b7 ' + parts.join(' \u00b7 ') : '') + '</span>'; },
    renderModelInfo: function () { var el = document.getElementById("interpModelInfo"); if (!el) return; var m = this.modelSelect ? this.modelSelect.value : "rife4.25-heavy", info = MODEL_INFO[m] || {}, tags = []; tags.push('<span class="meta-chip">' + (info.params || "5.1M") + '</span>'); tags.push('<span class="meta-chip">' + (info.quality || "High") + '</span>'); tags.push('<span class="meta-chip">' + (info.vram || "6GB") + ' VRAM</span>'); tags.push('<span class="meta-chip' + (m.indexOf("tensorrt") !== -1 ? ' meta-chip-accent' : '') + '"><i class="fa-solid fa-' + (m.indexOf("tensorrt") !== -1 ? 'bolt' : 'microchip') + '"></i> ' + (m.indexOf("tensorrt") !== -1 ? 'TensorRT' : 'CUDA') + '</span>'); el.innerHTML = '<span class="meta-strip meta-strip-sm">' + tags.join(' \u00b7 ') + '</span>'; },
    renderFactorInfo: function () { var el = document.getElementById("interpFactorInfo"); if (!el) return; var f = this.getFactor(), s = this._sourceInfo, fps = (s && s.ok) ? (s.frameRate || s.compFrameRate || 0) : 0, w = (s && s.ok) ? (s.width || 0) : 0, h = (s && s.ok) ? (s.height || 0) : 0, dur = (s && s.ok) ? (s.layerDuration || s.compDuration || s.duration || 0) : 0, frames = (s && s.ok && fps > 0 && dur > 0) ? Math.round(dur * fps) : 0, model = this.modelSelect ? this.modelSelect.value : "rife4.25-heavy", line = fps > 0 ? '<i class="fa-solid fa-arrow-right"></i> ' + fps.toFixed(2) + ' fps \u2192 <b class="meta-hi">' + (fps * f).toFixed(2) + ' fps</b>' : '<i class="fa-solid fa-arrow-right"></i> \u00d7<b>' + f + '</b> \u00b7 ' + (f - 1) + ' new frames per pair'; var eta = et(frames, w, h, f, model, true); if (eta) line += '<span style="margin-left:12px;font-size:8px;color:#aaaaaa;"><i class="fa-solid fa-clock"></i> ~' + eta.time + '</span>' + (eta.speed ? '<span style="margin-left:4px;font-size:8px;color:#888888;">' + eta.speed + ' fps</span>' : ''); el.innerHTML = '<span class="meta-strip meta-strip-sm">' + line + '</span>'; },
    startPreview: function () { var s = this._sourceInfo; if (!s || !s.ok) { window.showToast("Select a footage layer first", "error"); return; } var model = this.modelSelect ? this.modelSelect.value : "rife4.25-heavy", factor = this.getFactor(), renderDir = (this.app && this.app.settings.outputPath) || window.FileSystem.os.homedir(), escapedDir = String(renderDir).replace(/\\/g, "/"), self = this, btn = document.getElementById("previewInterpolateBtn"), pBar = document.getElementById("interpPreviewBar"), pFill = document.getElementById("interpPreviewFill"), pPct = document.getElementById("interpPreviewPercent"); if (btn) { btn.disabled = true; btn.textContent = "Rendering..."; } if (pBar) pBar.style.display = ""; if (pFill) pFill.style.width = "0%"; if (pPct) pPct.textContent = "0%"; window.__adobe_cep__.evalScript('renderSelectedLayerPreview("' + escapedDir + '", 3)', function (result) { if (btn) { btn.disabled = false; btn.textContent = "Preview"; } var res = {}; try { res = JSON.parse(result || "{}"); } catch (e) {} if (!res.ok || !res.filePath) { if (pBar) pBar.style.display = "none"; window.showToast(res.message || "Preview render failed", "error"); return; } var ext = window.FileSystem.getExtension(res.filePath), pp = window.FileSystem.path.join(renderDir, "AniSmooth_Preview_" + Date.now() + "." + ext); if (btn) { btn.disabled = true; btn.textContent = "Processing..."; } window.ModelHandler.interpolateClip(res.filePath, pp, model, { fpsFactor: String(factor) }, { onProgress: function (p) { if (btn) btn.textContent = p + "%"; if (pFill) pFill.style.width = p + "%"; if (pPct) pPct.textContent = p + "%"; }, onComplete: function () { if (pBar) pBar.style.display = "none"; if (btn) { btn.disabled = false; btn.textContent = "Preview"; } try { window.FileSystem.fs.unlinkSync(res.filePath); } catch (e) {} window.App.importFileToAfterEffects(pp); window.showConfirm("Preview imported. Delete preview file?", function () { try { window.FileSystem.fs.unlinkSync(pp); } catch (e) {} }); }, onError: function (err) { if (pBar) pBar.style.display = "none"; if (btn) { btn.disabled = false; btn.textContent = "Preview"; } try { window.FileSystem.fs.unlinkSync(res.filePath); } catch (e) {} window.showToast("Preview failed: " + err, "error"); } }); }); },
    addToQueue: function () { var s = this._sourceInfo; if (!s || !s.ok) { window.showToast("Select a footage layer first.", "error"); return; } var enableTargetSize = document.getElementById("interpEnableTargetSize"); var targetSize = (enableTargetSize && enableTargetSize.checked) ? (parseFloat(document.getElementById("interpTargetSize").value) || 0) : 0; var presetEl = document.getElementById("interpPreset"); var preset = presetEl ? presetEl.value : "high";       window.QueueManager.add({ mode: "interpolate", task: "Interpolation", name: s.layerName || s.name || "Footage", layerIndex: s.layerIndex || 0, model: this.modelSelect ? this.modelSelect.value : "rife4.25-heavy", factor: this.getFactor(), width: s.width || 0, height: s.height || 0, fps: s.frameRate || s.compFrameRate || 0, targetSizeMb: targetSize, preset: preset }); },
    _updateButtons: function (running) { if (this.cancelBtn) this.cancelBtn.style.display = running ? "" : "none"; }
  };
  var MODEL_INFO = { "rife4.25-heavy": { params: "5.1M", quality: "Best", vram: "6GB" }, "rife4.25": { params: "1.3M", quality: "High", vram: "2GB" }, "rife4.25-heavy-tensorrt": { params: "5.1M", quality: "Best", vram: "6GB" }, "rife4.25-tensorrt": { params: "1.3M", quality: "High", vram: "2GB" } };
  function esc(t) { var d = document.createElement("div"); d.appendChild(document.createTextNode(t || "")); return d.innerHTML; }
  function et(frames, w, h, factor, model, isInterp) { if (!frames || frames <= 0) return null; var pixels = (w || 1920) * (h || 1080), refPixels = 1920 * 1080, resScale = refPixels / Math.max(pixels, 1), baseFps = 25; if (model.indexOf("heavy") !== -1) baseFps = 12; if (model.indexOf("tensorrt") !== -1) baseFps *= 1.8; var gpuInfo = (window.App && window.App._gpuInfoCache), cuda = gpuInfo && gpuInfo.cuda_available; if (!cuda) baseFps *= 0.08; var ef = baseFps * resScale, wf = frames * (factor - 1), ts = wf / Math.max(ef, 0.1), m = Math.floor(ts / 60), s = Math.round(ts % 60); return { time: m > 0 ? m + "m " + s + "s" : s + "s", speed: ef.toFixed(1) }; }
  window.InterpolationPanel = InterpolationPanel;
})();
