(function () {
  var UpscalePanel = {
    init: function (app) { this.app = app; this.view = document.getElementById("upscaleView"); this.modelSelect = document.getElementById("upscaleModel"); this.scaleSelect = document.getElementById("upscaleScale"); this.startBtn = document.getElementById("startUpscaleBtn"); this._sourceInfo = null; this.bindEvents(); this._renderSafe("modelInfo"); this._renderSafe("scaleInfo"); },
    bindEvents: function () { var s = this; if (this.startBtn) this.startBtn.addEventListener("click", function () { s.addToQueue(); }); var pv = document.getElementById("previewUpscaleBtn"); if (pv) pv.addEventListener("click", function () { s.startPreview(); }); if (this.modelSelect) this.modelSelect.addEventListener("change", function () { s._renderSafe("modelInfo"); }); if (this.scaleSelect) this.scaleSelect.addEventListener("change", function () { s._renderSafe("scaleInfo"); }); },
    refreshLayerInfo: function () { var s = this; if (!window.__adobe_cep__ || !window.__adobe_cep__.evalScript) { if (s._sourceInfo !== null) { s._sourceInfo = null; s._renderSafe("layerInfo"); } return; } if (this._fetching) return; this._fetching = true; window.__adobe_cep__.evalScript("getSelectedLayerInfo()", function (r) { s._fetching = false; var raw = r || "{}"; if (raw === s._lastRaw) return; s._lastRaw = raw; try { s._sourceInfo = JSON.parse(raw); } catch (e) { s._sourceInfo = null; } s._renderSafe("layerInfo"); s._renderSafe("scaleInfo"); }); },
    _renderSafe: function (w) { try { if (w === "layerInfo") this.renderLayerInfo(); else if (w === "scaleInfo") this.renderScaleInfo(); else if (w === "modelInfo") this.renderModelInfo(); } catch (e) {} },
    renderLayerInfo: function () { var el = document.getElementById("upscaleLayerInfo"); if (!el) return; var s = this._sourceInfo; if (!s || !s.ok) { el.innerHTML = '<span class="meta-strip meta-strip-dim"><i class="fa-solid fa-layer-group"></i> Select a footage layer</span>'; return; } var w = s.width || 0, h = s.height || 0, sc = parseInt(this.scaleSelect ? this.scaleSelect.value : "2", 10), oW = w * sc, oH = h * sc, lb = oW > 0 ? rl(oW, oH) : ""; el.innerHTML = '<span class="meta-strip"><i class="fa-solid fa-film"></i> <b>' + esc(s.layerName || s.name || "") + '</b>' + (w > 0 ? ' \u00b7 <span>' + w + '<b>\u00d7</b>' + h + '</span>' : '') + (oW > 0 ? ' \u2192 <b class="meta-hi">' + oW + '\u00d7' + oH + '</b>' + (lb ? ' <span class="meta-dim">' + lb + '</span>' : '') : '') + '</span>'; },
    renderModelInfo: function () { var el = document.getElementById("upscaleModelInfo"); if (!el) return; var m = this.modelSelect ? this.modelSelect.value : "adore", info = UPSCALE_MODEL_INFO[m] || {}; el.innerHTML = '<span class="meta-strip meta-strip-sm"><span class="meta-chip">' + (info.params || "4M") + '</span> \u00b7 <span class="meta-chip">' + (info.quality || "High") + '</span> \u00b7 <span class="meta-chip">' + (info.vram || "3GB") + ' VRAM</span> \u00b7 <span class="meta-chip"><i class="fa-solid fa-microchip"></i> CUDA</span></span>'; },
    renderScaleInfo: function () { var el = document.getElementById("upscaleScaleInfo"); if (!el) return; var sc = parseInt(this.scaleSelect ? this.scaleSelect.value : "2", 10), s = this._sourceInfo, w = (s && s.ok) ? s.width : 0, h = (s && s.ok) ? s.height : 0, fps = (s && s.ok) ? (s.frameRate || s.compFrameRate || 0) : 0, dur = (s && s.ok) ? (s.layerDuration || s.compDuration || s.duration || 0) : 0, frames = (s && s.ok && fps > 0 && dur > 0) ? Math.round(dur * fps) : 0, model = this.modelSelect ? this.modelSelect.value : "adore", line = ''; if (w > 0 && h > 0) { var iPx = w * h, oPx = w * sc * h * sc; line = '<i class="fa-solid fa-arrow-right"></i> Pixels: ' + fp(iPx) + ' \u2192 <b class="meta-hi">' + fp(oPx) + '</b> \u00b7 ' + (sc * sc) + '\u00d7 increase'; } else { line = '<i class="fa-solid fa-arrow-right"></i> Each axis \u00d7<b>' + sc + '</b> \u00b7 ' + (sc * sc) + '\u00d7 more pixels'; } var eta = et(frames, w || 1920, h || 1080, sc, model, false); if (eta) line += ' <span style="font-size:8px;color:#aaaaaa;">~' + eta.time + (eta.speed ? ' \u00b7 ' + eta.speed + ' fps' : '') + '</span>'; el.innerHTML = '<span class="meta-strip meta-strip-sm">' + line + '</span>'; },
    startPreview: function () { var s = this._sourceInfo; if (!s || !s.ok) { window.showToast("Select a footage layer first", "error"); return; } var model = this.modelSelect ? this.modelSelect.value : "adore", scale = parseInt(this.scaleSelect ? this.scaleSelect.value : "2", 10), renderDir = (this.app && this.app.settings.outputPath) || window.FileSystem.os.homedir(), escapedDir = String(renderDir).replace(/\\/g, "/"), fps = s.frameRate || s.compFrameRate || 24, previewSec = Math.max(0.5, (5 / fps)), self = this, btn = document.getElementById("previewUpscaleBtn"), pBar = document.getElementById("upscalePreviewBar"), pFill = document.getElementById("upscalePreviewFill"), pPct = document.getElementById("upscalePreviewPercent"); if (btn) { btn.disabled = true; btn.textContent = "Rendering..."; } if (pBar) pBar.style.display = ""; if (pFill) pFill.style.width = "0%"; if (pPct) pPct.textContent = "0%"; window.__adobe_cep__.evalScript('renderSelectedLayerPreview("' + escapedDir + '", ' + previewSec.toFixed(2) + ')', function (result) { if (btn) { btn.disabled = false; btn.textContent = "Preview"; } var res = {}; try { res = JSON.parse(result || "{}"); } catch (e) {} if (!res.ok || !res.filePath) { if (pBar) pBar.style.display = "none"; window.showToast(res.message || "Preview render failed", "error"); return; } var ext = window.FileSystem.getExtension(res.filePath), pp = window.FileSystem.path.join(renderDir, "AniSmooth_Preview_" + Date.now() + "." + ext); if (btn) { btn.disabled = true; btn.textContent = "Processing..."; } window.ModelHandler.upscaleClip(res.filePath, pp, model, { scale: String(scale) }, { onProgress: function (p) { if (btn) btn.textContent = p + "%"; if (pFill) pFill.style.width = p + "%"; if (pPct) pPct.textContent = p + "%"; }, onComplete: function () { if (pBar) pBar.style.display = "none"; if (btn) { btn.disabled = false; btn.textContent = "Preview"; } try { window.FileSystem.fs.unlinkSync(res.filePath); } catch (e) {} window.App.importFileToAfterEffects(pp); window.showConfirm("Preview imported. Delete preview file?", function () { try { window.FileSystem.fs.unlinkSync(pp); } catch (e) {} }); }, onError: function (err) { if (pBar) pBar.style.display = "none"; if (btn) { btn.disabled = false; btn.textContent = "Preview"; } try { window.FileSystem.fs.unlinkSync(res.filePath); } catch (e) {} window.showToast("Preview failed: " + err, "error"); } }); }); },
    addToQueue: function () { var s = this._sourceInfo; if (!s || !s.ok) { alert("Select a footage layer first."); return; } var targetSize = parseFloat(document.getElementById("upscaleTargetSize").value) || 0; window.QueueManager.add({ mode: "upscale", task: "Upscale", name: s.layerName || s.name || "Footage", model: this.modelSelect ? this.modelSelect.value : "adore", scale: parseInt(this.scaleSelect ? this.scaleSelect.value : "2", 10), width: s.width || 0, height: s.height || 0, targetSizeMb: targetSize }); }
  };
  var UPSCALE_MODEL_INFO = { "adore": { params: "4M", quality: "High", vram: "3GB" }, "fallin_soft": { params: "3.9M", quality: "Best", vram: "4GB" } };
  function esc(t) { var d = document.createElement("div"); d.appendChild(document.createTextNode(t || "")); return d.innerHTML; }
  function fp(px) { if (px >= 1e6) return (px / 1e6).toFixed(1) + " MP"; return (px / 1e3).toFixed(0) + " KP"; }
  function rl(w, h) { if (h <= 480) return "SD"; if (h <= 720) return "HD"; if (h <= 1080) return "FHD"; if (h <= 1440) return "2K"; if (h <= 2160) return "4K"; if (h <= 4320) return "8K"; return ""; }
  function et(frames, w, h, factor, model, isInterp) { if (!frames || frames <= 0) return null; var pixels = (w || 1920) * (h || 1080), refPixels = 1920 * 1080, resScale = refPixels / Math.max(pixels, 1), baseFps = isInterp ? 25 : 15; if (model.indexOf("heavy") !== -1) baseFps = 8; var gpuInfo = (window.App && window.App._gpuInfoCache), cuda = gpuInfo && gpuInfo.cuda_available; if (!cuda) baseFps *= 0.08; var ef = baseFps * resScale, ts = frames / Math.max(ef, 0.1); if (isInterp) ts *= (factor - 1); var m = Math.floor(ts / 60), s = Math.round(ts % 60); return { time: m > 0 ? m + "m " + s + "s" : s + "s", speed: ef.toFixed(1) }; }
  window.UpscalePanel = UpscalePanel;
})();
